### ISSUE TITLE
love2d is unable to find the __temp file created by the JS code

### ISSUE THREAD

**Issue by Apurv-henkare** [MrcSnm/Love.js-Api-Player#4]
Love2D->JS works great (callJS function works well!)

However if I do this:
JS->write to indexedDB -> try to access indexedDB using Love.js file IO
love.js/love2d is unable to find the __temp file created by the JS code

**Comment by Apurv-henkare** [comment]
@abhimonk had proposed a solution. But am unable to understand.

**Comment by MrcSnm** [comment]
You need to open the love.js file, find the variable which mess with the file system. This variable is usually called `FS`. You need to make this available to the global window scope. As the newer versions of the love.js is actually run inside an anonymous function for not polluting the global scope, this variable is not available. This is a mini simulation of what you must do:

```js
window.FS = null;

(function theLoveJsCode()
{
   fs = something;
   //Modify it here 
   window.FS = fs;
})();
```

I could do a mini script for modifying the love js code, but I'm pretty busy ultimately

**Comment by Apurv-henkare** [comment]
I really don't know where to put the above code in love.js. Its pretty messy. @MrcSnm 
![image](https://user-images.githubusercontent.com/70956903/156923577-208c9bf7-1358-4b6b-a66e-7542bef14ccf.png)

**Comment by MrcSnm** [comment]
Share the file with me

**Comment by Apurv-henkare** [comment]
https://github.com/Apurv-henkare/Testing-Love.js/blob/main/game/love.js

Sorry for late reply @MrcSnm

**Comment by MrcSnm** [comment]
[fbdf10c](https://github.com/MrcSnm/Love.js-Api-Player/commit/fbdf10cd34875c642588c591aeb17c8b2764e131)

Brings a script to solve your issue, just execute `node globalizeFS.js` (love.js must be on the same folder as that file) and it should solve your problem

**Comment by Apurv-henkare** [comment]
![image](https://user-images.githubusercontent.com/70956903/156926483-c2e60ecf-dae4-4de4-b83e-a1e6aacf42f9.png)

**Comment by Apurv-henkare** [comment]
> [fbdf10c](https://github.com/MrcSnm/Love.js-Api-Player/commit/fbdf10cd34875c642588c591aeb17c8b2764e131)
> 
> Brings a script to solve your issue, just execute `node globalizeFS.js` (love.js must be on the same folder as that file) and it should solve your problem

thank you so much
