### ISSUE TITLE
console.info is not a function

### ISSUE THREAD

**Issue by lilmike** [MrcSnm/Love.js-Api-Player#5]
Hiya,

I'm trying this out for my love2d game, and I'm getting the following error in the js console:

```
Uncaught TypeError: console.info is not a function
    at game.js:260:25
    at getRequest.onsuccess (game.js:175:18)
```

Anything I can do to debug this?

Thanks,

-Michael.

**Comment by Mrestof** [comment]
Yeah, it's an easy bug to fix. The newly created wrapper console lacks the `.info` function defined. You just need to edit `consolewrapper.js` and add the `info` function by copying the behavior of the `warn` or `error` function.
